apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitreleases
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
  namespace: gitreleases
spec:
  tls:
    - hosts:
        - gitreleases.dev
      secretName: gitreleases-tls
  rules:
    - host: gitreleases.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitreleases
                port:
                  name: http
